// examples/vue/client/components/hero-insert.vue
<template>
<div class="insert">
    <form v-on:submit.prevent="onSubmit" name="insertForm">
        <input v-model="name" type="text" name="name" placeholder="Name" />
        <br/>
        <input v-model="color" type="text" name="color" placeholder="Color" />
        <br/>
        <button>Submit</button>
    </form>
</div>
</template>

<script>
import * as Database from '../database/Database';

export default {
    data: () => {
        return {
            name: '',
            color: ''
        };
    },
    methods: {
        async onSubmit() {
            console.log('OnSubmit');
            console.dir(this);
            const db = await Database.get();
            const obj = {
                name: this.name,
                color: this.color
            }
            console.dir(obj);
            await db.heroes.insert(obj);
            console.log('Inserted new hero: ' + this.name);

            this.name = '';
            this.color = '';
        }
    }
}
</script>


<style>
.insert {}
</style>

// examples/react/src/hero-insert/hero-insert.jsx
import React, {Component} from 'react';
import * as Database from '../Database';

class HeroInsert extends Component {
    state = {
        name: '',
        color: ''
    }
    subs = []

    addHero = async (event) => {
        event.preventDefault()
        const {name, color} = this.state;
        const db = await Database.get();
        db.heroes.insert({name, color});
        this.setState({name: '', color: ''});
    }
    handleNameChange = (event) => {
        this.setState({name: event.target.value});
    }
    handleColorChange = (event) => {
        this.setState({color: event.target.value});
    }

    render() {
        return (
            <div id="insert-box" className="box">
                <h3>Add Hero</h3>
                <form onSubmit={this.addHero}>
                    <input type="text" placeholder="Name" value={this.state.name} onChange={this.handleNameChange} />
                    <input type="text" placeholder="Color" value={this.state.color} onChange={this.handleColorChange}/>
                    <button type="submit">Insert a Hero</button>
                </form>
            </div>
        );
    }
}

export default HeroInsert;
