// examples/angular2/app/src/components/hero-insert/hero-insert.component.ts
import { Component, ViewChildren } from '@angular/core';
import { DatabaseService } from '../../services/database.service';
import * as randomInt from 'random-int';

@Component({
    selector: 'hero-insert',
    templateUrl: './hero-insert.component.html',
    styles: [String(require('./hero-insert.component.less'))],
    providers: [DatabaseService]
})
export class HeroInsertComponent {

    @ViewChildren('input') inputfield;

    name = '';
    color = '';

    constructor(
        private databaseService: DatabaseService
    ) {

    }



    async submit() {
        console.log('HeroInsertComponent.submit():');
        if (this.name == '' || this.color == '') return;

        const addDoc = {
            name: this.name,
            color: this.color,
            maxHP: randomInt(100, 1000),
            hp: 100
        };

        this.name = '';
        this.color = '';

        const db = await this.databaseService.get();
        db['hero'].insert(addDoc);

        this.inputfield.first._inputElement.nativeElement.focus();
    }


}

<form autocomplete="off">
    <input mdInput #input [(ngModel)]="name" [autofocus]="true" name="name" placeholder="Name" />
    <br/>
    <input mdInput [(ngModel)]="color" name="color" placeholder="Color" />
    <br/>
    <button md-raised-button color="primary" (click)=submit()>insert</button>
</form>

// examples/vue/src/components/hero-insert.vue
<template>
<div class="insert">
    <form v-on:submit.prevent="onSubmit" name="insertForm">
        <input v-model="name" autocomplete="off" type="text" name="name" placeholder="Name" />
        <br/>
        <input v-model="color" autocomplete="off" type="text" name="color" placeholder="Color" />
        <br/>
        <button>Submit</button>
    </form>
</div>
</template>

<script>
import Vue from 'vue';
import * as Database from '../database/Database';
import * as randomInt from 'random-int';

export default Vue.component('hero-insert', {
  data: () => {
      return {
          name: '',
          color: ''
      };
  },
  methods: {
      async onSubmit() {
          console.log('OnSubmit');
          console.dir(this);
          const db = await Database.get();
          const obj = {
              name: this.name,
              color: this.color,
              hp: 100,
              maxHP: randomInt(100, 1000)
          }
          console.dir(obj);
          await db.heroes.insert(obj);
          console.log('Inserted new hero: ' + this.name);

          this.name = '';
          this.color = '';
      }
  }
});
</script>


<style>
  input{
      font-size: 16px;
      font-weight: lighter;
      border: 0;
      border-bottom: 1px solid #999;
      margin-bottom: 20px;
      padding-bottom: 7px;
  }
  input:focus{
      outline: none;
  }
  button{
      background-color: #009688;
      outline: none;
      border: none;
      color: white;
      font-size: 16px;
      border-radius: 4px;
      padding: 1.5%;
      cursor: pointer;
      box-shadow: 0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 5px 0px rgba(0, 0, 0, 0.12);
  }
</style>
