// examples/angular/src/app/components/hero-edit/hero-edit.component.ts
import {
    Component,
    Input,
    Output,
    EventEmitter,
    OnInit,
    ChangeDetectorRef,
    Inject
} from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import {
    Subscription
} from 'rxjs';
import {
    skip
} from 'rxjs/operators';
import { RxHeroDocument } from 'src/app/RxDB';

@Component({
    selector: 'hero-edit',
    templateUrl: './hero-edit.component.html',
    styleUrls: ['./hero-edit.component.less'],
    providers: [],
})
export class HeroEditDialogComponent implements OnInit {
    public synced: boolean = true;
    public formValue = 0;
    private subs: Subscription[] = [];

    constructor(
        private cdr: ChangeDetectorRef,
        public dialogRef: MatDialogRef<HeroEditDialogComponent>,
        @Inject(MAT_DIALOG_DATA) public data: {
            hero: RxHeroDocument
        }
    ) {
        this.synced = true;
    }

    ngOnInit() {
        if (!this.data.hero) {
            console.dir(this.data);
            throw new Error('hero is missing');
        }
        this.formValue = this.data.hero.hp;
        this.subs.push(
            this.data.hero.$
                .pipe(
                    skip(1)
                )
                .subscribe(() => {
                    this.synced = false;
                    this.cdr.detectChanges();
                })
        );
    }

    async submit() {
        if (!this.data.hero) {
            throw new Error('should never happen');
        }

        await this.data.hero.atomicPatch({ hp: this.formValue });
        this.dialogRef.close();
    }

    resync() {
        if (!this.data.hero) {
            throw new Error('should never happen');
        }
        this.formValue = this.data.hero.hp;
        this.synced = true;
        this.cdr.detectChanges();
    }

    async cancel() {
        this.dialogRef.close();
    }

    ngOnDestroy() {
        this.subs.forEach(sub => sub.unsubscribe());
    }
}

<mat-card
    *ngIf="data.hero"
    class="hero-edit-component"
>
    <mat-card-subtitle>Edit</mat-card-subtitle>

    <div
        class="alert"
        *ngIf="!synced"
    >
        <h4>Warning:</h4>
        <p>Someone else has <b>changed</b> this document. If you click save, you will overwrite the changes.</p>
        <button
            mat-raised-button
            color="primary"
            (click)=resync()
        >resync</button>
    </div>

    <div
        class="alert deleted"
        *ngIf="(data.hero.deleted$ | async)"
    >
        <h4>Error:</h4>
        <p>Someone else has <b>deleted</b> this document. You can not save anymore.</p>
    </div>

    <h5>
        <div
            class="color-box"
            [style.background-color]="data.hero.color"
        ></div>
        {{data.hero.name}}
    </h5>


    <mat-form-field>
        HP: <input
            matInput
            type="number"
            [(ngModel)]="formValue"
            min="0"
            [max]="data.hero.maxHP"
            name="hp"
        />
    </mat-form-field>

    <br />
    <button
        mat-raised-button
        color="primary"
        (click)="cancel()"
    >cancel</button>
    <button
        *ngIf="!(data.hero.deleted$ | async)"
        class="submitButton"
        mat-raised-button
        color="primary"
        (click)=submit()
    >submit</button>

</mat-card>

// examples/vue/src/components/hero-edit.vue
<template>
<div id="edit-box" class="hero-edit box">
    <h4>Edit</h4>
    <div class="alert" v-if="!synced">
        <h4>Warning:</h4>
        <p>Someone else has <b>changed</b> this document. If you click save, you will overwrite the changes.</p>
        <button v-on:click="resync()">resync</button>
    </div>
    <div class="alert deleted" v-if="hero.deleted">
        <h4>Error:</h4>
        <p>Someone else has <b>deleted</b> this document. You can not save anymore.</p>
    </div>
    <h5>
      <div class="color-box" v-bind:style="{ backgroundColor: hero.color }"></div>
      {{hero.name}}
  </h5> HP: <input id="hp-edit-input" type="number" v-model.number="formData" min="0" v-bind:max="hero.maxHP" name="hp" />
    <br />
    <button v-on:click="cancel()">cancel</button>
    <button id="edit-submit-button" v-on:click="submit()" v-if="!hero.deleted">submit</button>
</div>
</template>

<script>
import Vue from 'vue';
import * as Database from '../database/Database';
import {
    skip
} from 'rxjs/operators';

export default Vue.component('hero-edit', {
    data: () => {
        return {
            synced: true,
            deleted: false,
            formData: null,
            subs: []
        };
    },
    props: ['hero'],
    mounted: async function() {
        this.formData = this.hero.hp;
        this.subs.push(
            this.hero.$
            .pipe(
                skip(1)
            )
            .subscribe(() => this.synced = false)
        );
    },
    beforeDestroy: function() {
        this.subs.forEach(sub => sub.unsubscribe());
    },
    methods: {
        async submit() {
            console.log('heroEdit.submit()');
            await this.hero.atomicSet('hp', this.formData);
            this.$emit('submit');
        },
        resync() {
            console.log('heroEdit.resync()');
            this.hero.resync();
        },
        cancel() {
            console.log('heroEdit.cancel()');
            this.hero.resync();
            this.$emit('cancel');
        }
    }
});
</script>


<style>
.hero-edit {
    position: fixed;
    z-index: 10;
    width: 70%;
    margin-left: 10%;
    min-height: 200px;
    margin-top: -5px;
    padding: 20px;
}

.alert {
    border-style: solid;
    border-width: 2px;
    border-radius: 10px;
    padding: 8px;
    border-color: #e0e021;
    &.deleted {
        border-color: red;
    }
    h4 {
        padding: 0;
        margin: 0;
    }
}

.color-box {
    width: 20px;
    height: 20px;
    float: left;
    margin-right: 11px;
    border-radius: 2px;
    border-width: 1px;
    border-style: solid;
    border-color: grey;
}
</style>
