// examples/vue/src/components/heroes-list.vue
<template>
<div class="heroes-list">
    <ul v-if="results">
        <li v-for="hero in results">
            <div class="color-box" v-bind:style="{ backgroundColor: hero.color }"></div>
            {{ hero.name }}
            <div class="life">
                <div class="currentPercent" v-bind:style="{ width: hero.hpPercent() +'%' }"></div>
            </div>
            <div class="actions">
                <i class="fa fa-pencil-square-o" aria-hidden="true" v-on:click="editHero(hero)"></i>
                <i class="fa fa-trash-o" aria-hidden="true" v-on:click="removeHero(hero)"></i>
            </div>
        </li>
    </ul>
    <span v-else>Loading..</span>

</div>
</template>

<script>
import Vue from 'vue';
import * as Database from '../database/Database';
export default Vue.component('heroes-list', {
    data: () => {
        return {
            results: [],
            subs: []
        };
    },
    mounted: async function() {
        const db = await Database.get();
        this.subs.push(
            db.heroes
            .find().$
            .filter(x => x != null)
            .subscribe(results => {
                console.log('results:');
                //                console.dir(results);
                this.results = results;
            })
        );
    },
    beforeDestroy: function() {
        this.subs.forEach(sub => sub.unsubscribe());
    },
    methods: {
        removeHero(hero) {
            hero.remove();
        },
        editHero(hero) {
            this.$emit('edit', hero);
        }
    }
});
</script>


<style>
ul {
    list-style: none;
    padding: 0 16px;
    display: inline-block;
    position: relative;
    width: 100%;
}

ul li {
    width: 100%;
    float: left;
    margin-top: 6px;
    margin-bottom: 6px;
}

.color-box {
    width: 20px;
    height: 20px;
    float: left;
    margin-right: 11px;
    border-radius: 2px;
    border-width: 1px;
    border-style: solid;
    border-color: grey;
}

.life {
    width: 85%;
    height: 2px;
    background-color: red;
    float: left;
    position: absolute;
    margin-left: 4%;
    left: 10px;
}

.life .currentPercent {
    height: 100%;
    background-color: green;
}

.actions {
    float: right;
}

.actions i {
    cursor: pointer;
}
</style>

// examples/angular2/app/src/components/heroes-list/heroes-list.component.ts
import { Component, OnInit, OnDestroy, NgZone, Output, EventEmitter } from '@angular/core';
import { DatabaseService } from '../../services/database.service';
import * as RxDBTypes from '../../RxDB.d';

@Component({
    selector: 'heroes-list',
    templateUrl: './heroes-list.component.html',
    styles: [String(require('./heroes-list.component.less'))],
    providers: [DatabaseService]
})
export class HeroesListComponent implements OnInit, OnDestroy {


    heroes: RxDBTypes.RxHeroDocument[] | RxDBTypes.RxHeroDocument;
    sub;

    @Output('edit') editChange: EventEmitter<RxDBTypes.RxHeroDocument> = new EventEmitter();
    set edit(hero) {
        console.log('editHero: ' + hero.name);
        this.editChange.emit(hero);
    }
    editHero(hero) {
        this.edit = hero;
    }
    deleteHero(hero) {
        hero.remove();
    }

    constructor(
        private databaseService: DatabaseService,
        private zone: NgZone
    ) {
    }

    ngAfterContentInit() { }

    private async _show() {
        const db = await this.databaseService.get();
        const heroes$ = db.hero
            .find()
            .sort({ name: 1 })
            .$;
        this.sub = heroes$.subscribe(heroes => {
            this.heroes = heroes;
            this.zone.run(() => { });
        });
    }

    ngOnInit() {
        this._show();
    }

    ngOnDestroy() {
        this.sub.unsubscribe();
    }
}

<div class="loading" *ngIf="!emittedFirst" class="hero-list-component">
    <mat-spinner class="app-spinner"></mat-spinner>
</div>

<mat-list class="hero-list-component">
    <mat-list-item *ngFor="let hero of heroes$ | async as heroes; index as i" class="listHero">
        <div class="color-box" [style.background-color]="hero.color"></div>
        <div class="name">
          {{hero.name}}
          <div class="life">
            <div class="currentPercent" [style.width]="hero.hpPercent() + '%'"></div>
          </div>
        </div>
        <div class="actions">
            <i class="fa fa-pencil-square-o" aria-hidden="true" (click)="editHero(hero)"></i>
            <i class="fa fa-trash-o" aria-hidden="true" (click)="deleteHero(hero)"></i>
        </div>
    </mat-list-item>
</mat-list>
